[package]
name = "flux-windows-screensaver"
version = "0.1.0"
edition = "2021"

[dependencies]
flux = { version = "1", git = "https://github.com/sandydoo/flux", branch = "main" }
glow = "0.11.2"
glutin = "0.28.0"

