[package]
name = "flux-windows-screensaver"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
env_logger = "0.9"
flux = { version = "2", git = "https://github.com/sandydoo/flux", branch = "main" }
glow = "0.11.2"
log = "0.4"
raw-window-handle = "0.4"
sdl2-sys = "0.35.2"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = [ "static-link", "raw-window-handle" ]

[dependencies.winapi]
version =  "0.3"
features = [ "winuser", "winerror", "shellscalingapi" ]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

# [patch."https://github.com/sandydoo/flux"]
# flux = { version = "2", path = "../../flux/crates/flux" }
