name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features  --target x86_64-pc-windows-gnu
    - run: nix develop --impure
    - run: cd windows
    - run: cargo build
